version: "3.9"
services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

volumes:
  postgres1_data:
  postgres2_data:
